# IMAGEN MODELO
FROM eclipse-temurin:17.0.15_6-jdk

#INFORMACION DEL PUERTO
#8080:8091
EXPOSE 8091

# CREAR EL DIRECTORIO RAIS DEL CONTENEDOR
WORKDIR /app

# COPIAR Y PAGER EL ARCHIVO DENTRO DEL DIRECTORIO DEL CONTENEDOR
# COPIA EL "pom.xml", DENTRO DEL DIRACTORIO RAIS "/app"
# COPIA "MAVEN" DE "./mvn", DENTRO DE LA RAIS "/app", EN LA CARPETA "/.mvn"
# COPIA EL EJECUTABLE DE MAVEN "./mvnm", DENTRO DEL "/app"
COPY ./pom.xml /app
COPY ./.mvn /app/.mvn
COPY ./mvnw /app

#DESCARGAR LAS DEPENDENCIA, DENTRO DEL CONTENDOR
RUN ./mvnw dependency:go-offline

#COPIA EL CODIGO FUENTE, DENTRO DEL CONTENEDOR "/app/src"
COPY ./src /app/src

#CONSTRUIR LA APLICACION
#SALTA LOS TEST UNITARIO
RUN ./mvnw clean install -DskipTests

#LEVANTAR NUESTRA APLICACION, CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java", "-jar", "/app/target/crud-carnet-0.0.1-SNAPSHOT.jar"]